# Generated by Django 4.0.6 on 2022-07-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score_hist',
            unique_together=set(),
        ),
    ]
