# Generated by Django 4.0.6 on 2022-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_score_hist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_hist',
            name='rating',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
