# Generated by Django 4.0.6 on 2022-07-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_score_hist_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score_hist',
            unique_together=set(),
        ),
    ]
