# Generated by Django 4.0.6 on 2022-12-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_score_hist_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='repling_to',
        ),
        migrations.AddField(
            model_name='comment',
            name='replying_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replying', to='base.comment'),
        ),
    ]
