# Generated by Django 4.0.6 on 2022-12-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_comment_repling_to_comment_replying_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_hist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c', to=settings.AUTH_USER_MODEL),
        ),
    ]
