# Generated by Django 4.0.6 on 2022-12-21 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_score_hist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_hist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c', to=settings.AUTH_USER_MODEL),
        ),
    ]
